build(deps): Bump pre-commit autoupdate
Also add pyjson5 as an additional dependency for check-jsonschema pre-commit;
I'm hoping that this will fix the following error seen (only) on CI (not locally):

Validate Renovate Config.................................................Failed
- hook id: check-renovate
- exit code: 1

Several files failed to parse.
  BadFileTypeError: cannot parse .renovaterc.json5 because support is missing for json5

  check-jsonschema can only parse json5 files when a json5 parser is installed

  If you are running check-jsonschema as an installed python package, either
      pip install json5
  or
      pip install pyjson5

  If you are running check-jsonschema as a pre-commit hook, set
      additional_dependencies: ['json5']
  or
      additional_dependencies: ['pyjson5']

    in "/home/runner/.cache/pre-commit/repothldx688/py_env-python3/lib/python3.12/site-packages/check_jsonschema/instance_loader.py", line 48
    >>> data: t.Any = self._parsers.parse_data_with_path(

I've chosen https://github.com/Kijewski/pyjson5 instead of https://github.com/dpranke/pyjson5 because the former seems to slower than latter with cython.